### ISSUE TITLE
no no button

### ISSUE THREAD

**Issue by ghost** [springweblobby/swl-qt#21] opened 2016-03-12 15:41 UTC
When a vote for many options is on I see the voting dialog this way:
![too fat voting dialog bug](https://cloud.githubusercontent.com/assets/6011365/13723817/534ec5ea-e879-11e5-9698-3d7f1794e1af.png)

**Comment by db81** [comment] 2016-03-13 02:25
Duplicate of springweblobby/swl-website#49.

**Closed as completed by db81** 2016-03-13 02:25 UTC
Labels: duplicate
